package buttonbox

type buttonID uint

const (
	enc1Pos    = buttonID(32)
	enc1Neg    = buttonID(31)
	enc2Pos    = buttonID(30)
	enc2Neg    = buttonID(29)
	enc3Pos    = buttonID(27)
	enc3Neg    = buttonID(28)
	enc4Pos    = buttonID(25)
	enc4Neg    = buttonID(26)
	button1    = buttonID(3)
	button2    = buttonID(8)
	button3    = buttonID(13)
	button4    = buttonID(18)
	button5    = buttonID(23)
	button6    = buttonID(22)
	button7    = buttonID(21)
	button8    = buttonID(0)
	button9    = buttonID(5)
	button10   = buttonID(10)
	button11   = buttonID(15)
	button12   = buttonID(20)
	switch1Pos = buttonID(2)
	switch1Neg = buttonID(4)
	switch2Pos = buttonID(12)
	switch2Neg = buttonID(14)
	switch3Pos = buttonID(6)
	switch3Neg = buttonID(7)
	switch4Pos = buttonID(16)
	switch4Neg = buttonID(17)
)
